name: my_first_actions
on: workflow_dispatch 
jobs:
  first_yml_action:
    runs-on: ubuntu-latest
    steps:
      - name: prints greetings
        run: echo "hello there"
      - name: prints bye
        run: echo "Good Bye"
